apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vsmcp-prod

bases:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml

configMapGenerator:
- name: vsmcp-config
  behavior: merge
  literals:
  - VSMCP_LOG_LEVEL=warn
  - TELEMETRY_ENABLED=true
  - CLUSTER_NODES=prod-vsmcp-0.prod-vsmcp-headless,prod-vsmcp-1.prod-vsmcp-headless,prod-vsmcp-2.prod-vsmcp-headless

secretGenerator:
- name: vsmcp-secrets
  behavior: replace
  envs:
  - secrets.env

replicas:
- name: vsmcp
  count: 5

images:
- name: vsmcp
  newTag: 0.1.0