apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsmcp-data
  namespace: vsmcp
  labels:
    app.kubernetes.io/name: vsmcp
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard