apiVersion: v1
kind: ServiceAccount
metadata:
  name: vsmcp
  namespace: vsmcp
  labels:
    app.kubernetes.io/name: vsmcp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vsmcp
  namespace: vsmcp
  labels:
    app.kubernetes.io/name: vsmcp
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vsmcp
  namespace: vsmcp
  labels:
    app.kubernetes.io/name: vsmcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vsmcp
subjects:
- kind: ServiceAccount
  name: vsmcp
  namespace: vsmcp