apiVersion: v1
kind: Secret
metadata:
  name: vsmcp-secrets
  namespace: vsmcp
  labels:
    app.kubernetes.io/name: vsmcp
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Node configuration
  RELEASE_COOKIE: "change-me-to-secure-cookie"
  
  # Database credentials
  DATABASE_URL: "postgresql://vsmcp:password@postgres:5432/vsmcp_prod"
  
  # AMQP credentials
  AMQP_URL: "amqp://vsmcp:password@rabbitmq:5672/vsmcp"
  
  # API keys (add as needed)
  # OPENAI_API_KEY: ""
  # ANTHROPIC_API_KEY: ""