apiVersion: v1
kind: Service
metadata:
  name: vsmcp
  namespace: vsmcp
  labels:
    app.kubernetes.io/name: vsmcp
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: http
    protocol: TCP
    name: http
  - port: 5000
    targetPort: mcp
    protocol: TCP
    name: mcp
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: vsmcp
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: vsmcp-headless
  namespace: vsmcp
  labels:
    app.kubernetes.io/name: vsmcp
    app.kubernetes.io/component: backend
spec:
  clusterIP: None
  ports:
  - port: 4369
    targetPort: epmd
    protocol: TCP
    name: epmd
  selector:
    app.kubernetes.io/name: vsmcp
    app.kubernetes.io/component: backend